const fs = require('fs');
const path = require('path');

const grokOutput = {
  "mombasa": "Deployment along the Northern Transit Corridor required capacitive fuel probe recalibration at 15-minute intervals to isolate volumetric discrepancies caused by temperature swings exceeding 12°C between coastal humidity and inland arid zones. Dual-SIM anti-jamming gateways streaming J1939 CAN-bus frames via sub-second MQTT prevented signal loss during multi-day bulk commodity hauls from the Port of Mombasa.",
  "nairobi": "High-density traffic on the East African Inland Logistics Hub forced implementation of edge-processed accelerometer fusion to detect unauthorized trailer decoupling events within 800 ms. Integration of encrypted OBD-II decryptors with cellular failover reduced false-positive geofence breaches by filtering multipath GNSS errors common in the central business district canyons.",
  "lagos": "On the Lagos-Ibadan-Kano Freight Highway, vibration spectra above 18 Hz necessitated hardened mounting of capacitive fuel sensors to maintain probe linearity during continuous high-axle-load operations. MQTT event queues synchronized with digital tachograph data streams enabled real-time detection of route deviations exceeding 3 km from planned corridors.",
  "kano": "Sahel cross-border segments demanded dual-frequency GNSS receivers with anti-spoofing firmware to counteract intermittent satellite occlusion near border posts. Fuel-level anomaly algorithms calibrated against ambient dust ingress thresholds flagged siphoning attempts by correlating sudden capacitance drops with stationary engine-idle states longer than 90 seconds.",
  "johannesburg": "Gauteng industrial distribution routes required CAN-bus gateway firmware updates to parse proprietary OEM J1939 PGNs for real-time axle-load monitoring under variable payload conditions. Sub-second MQTT streaming of door-sensor state changes detected unauthorized cargo access during overnight yard dwell periods.",
  "durban": "Container terminal handovers at the Durban Freight Corridor imposed strict latency budgets under 400 ms for RFID tag reads synchronized with telematics position fixes. Capacitive probe arrays compensated for salinity-induced dielectric shifts when units transitioned between maritime and inland environments.",
  "warsaw": "TEN-T north-south transit demanded multi-constellation GNSS with RTK correction feeds to maintain lane-level accuracy through urban multipath zones. J1939 decryption modules extracted brake temperature and retarder duty cycles to flag thermal stress events on sustained downhill gradients.",
  "krakow": "Cross-border freight segments required dual-SIM gateways with automatic APN failover to maintain continuous MQTT connectivity across operator coverage gaps. Edge logic correlating fuel-rate anomalies with GPS velocity vectors isolated engine-idling theft patterns during customs dwell intervals.",
  "bucharest": "Balkan Transit Corridor operations integrated barometric pressure sensors with GNSS altitude data to detect unauthorized high-elevation detours. CAN-bus parsing of fuel-rail pressure and injector pulse-width parameters enabled early identification of adulterated diesel events.",
  "constanta": "Black Sea port-to-Danube transfers necessitated IP68-rated sensor housings resistant to salt-spray corrosion while streaming container seal integrity events. Sub-second MQTT payloads carried dual accelerometer and gyroscope fusion outputs to classify handling shocks exceeding 4 g during crane lifts.",
  "budapest": "Highway crossroads density forced adaptive geofencing polygons that dynamically expanded based on real-time traffic density feeds. J1939 gateways decrypted transmission temperature and torque converter slip data to predict overheating risk during prolonged stop-start cycles.",
  "dubai": "Jebel Ali Port operations required active thermal compensation algorithms for capacitive fuel probes operating in ambient temperatures above 48°C to counteract dielectric constant drift. Dual-SIM anti-jamming modules maintained MQTT session continuity during high-power RF interference zones near industrial complexes.",
  "abu-dhabi": "Khalifa Port oil-and-gas supply chains demanded intrinsically safe sensor interfaces compliant with ATEX zone classifications while streaming J1939 engine-hour and fuel-consumption PGNs. Edge anomaly detection flagged volumetric losses correlated with prolonged stationary periods under high solar loading.",
  "mexico-city": "US-Mexico cross-border highway segments required encrypted dual-SIM gateways to resist targeted RF jamming common on high-risk corridors. Accelerometer threshold triggers combined with door-contact state machines detected cargo intrusion events within 1.2 seconds of breach.",
  "sao-paulo": "Mercosur corridor traffic imposed continuous CAN-bus monitoring of turbocharger boost and exhaust-gas temperature to identify forced high-load operation indicative of schedule pressure. MQTT event streams synchronized fuel-probe readings with toll-plaza geofence crossings for discrepancy isolation.",
  "bogota": "Andean highway altitude variations exceeding 2 600 m necessitated barometric recalibration of fuel-volume algorithms to correct for pressure-induced tank deformation. Dual-frequency GNSS with anti-spoofing firmware countered signal manipulation attempts on Buenaventura access routes.",
  "barcelona": "Mediterranean corridor port gateways required sub-second RFID-to-telematics handshakes for container handover validation. Capacitive probes compensated for marine humidity ingress by applying real-time dielectric offset corrections derived from onboard temperature-humidity sensors.",
  "hamburg": "Port of Hamburg rail-transfer nodes demanded precise timestamp alignment between GNSS fixes and digital twin yard maps to within 150 ms. J1939 gateways extracted inter-axle differential lock status and suspension pressure to verify load distribution prior to barge loading.",
  "rotterdam": "Rhine logistics axis operations integrated waterway AIS feeds with road telematics via MQTT topic bridging for multimodal continuity. Capacitive fuel arrays with temperature-compensated lookup tables maintained ±0.8 % volumetric accuracy across barge-to-truck transfer cycles.",
  "singapore": "Transshipment hub density required multi-constellation GNSS with SBAS corrections to resolve meter-level positioning inside dense container stacks. Dual-SIM gateways enforced TLS 1.3 session persistence while streaming seal-integrity and door-state events at 500 ms intervals.",
  "kuala-lumpur": "Peninsular expressway segments imposed continuous monitoring of engine coolant temperature and fan-clutch duty cycles under tropical heat-soak conditions. Edge logic correlating sudden fuel-level drops with zero-velocity states isolated roadside siphoning within 45 seconds.",
  "cairo": "Suez Canal network operations required dust-ingress-resistant sensor enclosures while parsing J1939 DPF soot-load and regeneration-status PGNs. MQTT payloads carried combined GNSS and inertial dead-reckoning solutions to bridge satellite outages inside urban canyon segments.",
  "casablanca": "Tanger-Med corridor traffic demanded dual-SIM automatic roaming profiles to maintain continuous connectivity across Mediterranean operator boundaries. Capacitive probe calibration curves adjusted for diurnal temperature swings of 22°C to preserve volumetric resolution.",
  "medellin": "Andean mountain pass gradients exceeding 8 % forced continuous logging of engine load percentage and transmission gear ratios via J1939. Dual-axis inclinometer fusion with GNSS altitude data detected unauthorized shortcut routes through secondary passes.",
  "santos": "Port of Santos to inland corridor transfers required shock-event classification algorithms running on 100 Hz accelerometer streams to identify excessive container handling. Fuel-probe data synchronized with crane-cycle timestamps isolated volumetric anomalies occurring exclusively during dwell periods.",
  "riyadh": "East-West desert logistics demanded active thermal management of gateway enclosures to keep internal temperatures below 70°C under solar loading. Capacitive fuel sensors applied real-time vapor-pressure compensation derived from tank-headspace temperature readings.",
  "perth": "Western Australia mining corridors required ruggedized dual-SIM modules with satellite-backup failover for coverage gaps exceeding 120 km. J1939 parsing of engine hours and idle-time counters quantified non-productive fuel burn during remote staging operations.",
  "johor-bahru": "Malaysia-Singapore cross-border queues imposed continuous monitoring of cabin door and cargo-door contact states to detect unauthorized access during extended border dwell. MQTT event streams carried differential GNSS solutions corrected for multipath near dense customs infrastructure.",
  "jeddah": "Red Sea port and Mecca logistics routes required IP67 sensor suites resistant to high ambient humidity and salt aerosols. Edge algorithms correlated fuel-rate anomalies with GNSS velocity profiles to isolate intentional idling versus congestion-induced delays.",
  "dammam": "Eastern Province oil-and-gas network operations mandated intrinsically safe CAN-bus interfaces while streaming proprietary OEM diagnostic trouble codes. Capacitive probes with multi-point temperature compensation maintained accuracy across diurnal swings exceeding 25°C on desert hauls."
};

const locationsPath = path.join(__dirname, 'data', 'locations.js');
let content = fs.readFileSync(locationsPath, 'utf8');

for (const [slug, newCaseStudy] of Object.entries(grokOutput)) {
  const safeText = newCaseStudy.replace(/'/g, "\\'");
  const regex = new RegExp(`(slug:\\s*'${slug}'[\\s\\S]*?localCaseStudy:\\s*')[^']+(')`, 'm');
  content = content.replace(regex, `$1${safeText}$2`);
}

fs.writeFileSync(locationsPath, content, 'utf8');
console.log('Successfully patched localCaseStudy fields.');
